site_name: E-Cell4 documentation
pages:
- Home: 'index.md'
- Installation: 'installation.md'
- Tutorials: 'tutorials.md'
- API:
    - 'core': 'api/core.md'
    - 'gillespie': 'api/gillespie.md'
    - 'ode': 'api/ode.md'
    - 'meso': 'api/meso.md'
    - 'lattice': 'api/lattice.md'
    - 'bd': 'api/bd.md'
