version: 2.1
executors:
  default:
    working_directory: ~/circle
    docker:
      - image: ghcr.io/ecell/image
    environment:
      ECELLVER: "2.1.0b2"
      BOOSTVER: "1.73.0"
      BOOSTFILE: "boost_1_73_0"
jobs:
  build:
    executor: default
    parameters:
      pyver:
        type: enum
        enum: ["cp36-cp36m", "cp37-cp37m", "cp38-cp38"]
    steps:
      - setup_remote_docker
      - checkout
      - run: |
          git submodule sync
          git submodule update --init --remote
      - run:
          name: Install Dependencies
          command: |
            set -x
            curl -L -o $BOOSTFILE.tar.bz2 https://dl.bintray.com/boostorg/release/$BOOSTVER/source/$BOOSTFILE.tar.bz2
            tar xf $BOOSTFILE.tar.bz2
            cd ~/circle
      - run:
          name: Install auditwheel from source
          command: |
            git clone https://github.com/pypa/auditwheel.git
            /opt/python/<< parameters.pyver >>/bin/python -m pip install ./auditwheel
      - run:
          name: Build E-Cell4
          command: |
            export BOOST_INCLUDEDIR=/root/circle/$BOOSTFILE
            /opt/python/<< parameters.pyver >>/bin/python setup.py bdist_wheel
            /opt/python/<< parameters.pyver >>/bin/auditwheel repair /root/circle/dist/ecell4_base-$ECELLVER-<< parameters.pyver >>-linux_x86_64.whl
      - store_artifacts:
          path: /root/circle/wheelhouse

workflows:
  version: 2
  build_wheels:
    jobs:
      - build:
          name: build_py36
          pyver: cp36-cp36m
      - build:
          name: build_py37
          pyver: cp37-cp37m
      - build:
          name: build_py38
          pyver: cp38-cp38
