name: Create Release

on: [push] # TODO

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ecell4_base
        uses: actions/checkout@v2
        with:
          path: ecell4_base
      - name: Checkout submodules
        run: |
          auth_header="$(git config --local --get http.https://github.com/.extraheader)"
          git submodule sync --recursive
          git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1
        working-directory: ./ecell4_base
      - name: Archive codes into ecell4_base.tar.gz
        run: |
          tar -zcvf ecell4_base.tar.gz -X ecell4_base/exclude_files ecell4_base
      - name: Test the archive is ok
        run: |
          ls -lh ecell4_base.tar.gz
